/*
hcircify - Spotify Now Playing plugin for HexChat

Copyright (C) 2015  M. Richards
Copyright (C) 2014  K. Leonardsen / Equalify.me

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

Contact info: mrichards@gmail.com
*/

#include "gitversion.h" //this file is autogenerated by my build scripts..
#define STRINGSIZE2(s) #s
#define STRINGSIZE(s) STRINGSIZE2(s) 

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_REVISION 4it
#define VERSION_BUILD VER_BUILD

#define VER_FILE_VERSION VERSION_MAJOR, VERSION_MINOR, VERSION_REVISION, VERSION_BUILD

#define VER_FILE_VERSION_STR STRINGSIZE(VERSION_MAJOR) \
	"." STRINGSIZE(VERSION_MINOR) \
	"." STRINGSIZE(VERSION_REVISION) \
	"." STRINGSIZE(VERSION_BUILD)

#ifdef _WIN64
#define VER_ORIGINAL_FILE_NAME_STR "hcircify_x64.dll"

#else
#define VER_ORIGINAL_FILE_NAME_STR "hcircify.dll"
#endif

#define VER_PRODUCT_NAME_STR "hcircify"
#define VER_FILE_DESCRIPTION_STR "Spotify Now Playing plugin for HexChat"
#define VER_INTERNAL_NAME_STR "hcircify"
#define VER_COPYRIGHT_STR "Copyright (C) 2015"
#define VER_PRODUCT_VERSION VER_FILE_VERSION
#define VER_PRODUCT_VERSION_STR VER_FILE_VERSION_STR
